### ISSUE TITLE
[Bug]: Incorrect window sizes

### ISSUE THREAD

**Issue by QwertzG** [hiaaryan/wora#22]
### What Happened?

My pc cannot get the app to be in its right proportions and im not able to resize it for whatever reason.

### Wora Version

0.3.3

### Operating System

windows 10

### Steps to Reproduce

open the app

### Severity

Minor

### Screenshots/Logs

![image](https://github.com/hiaaryan/wora/assets/105913565/81273208-bf19-42a2-9524-270b6cbee9a5)

### Discord Username

qwertz__

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hiaaryan** [comment]
Right. So currently, there is a minimum width & height set for the window which is causing this issue. I believe you are using a smaller monitor? If so, let me know what resolution.

**Comment by QwertzG** [comment]
mine is 1920x1080
i dont believe scrollbars appear in fullscreen but im not too sure since i can see that side of the app
cant wait for the update

**Comment by hiaaryan** [comment]
Just keeping this open till the issue is resolved and the update is released.

**Comment by gabeweb** [comment]
Hi.

In my "old-school" laptop (1366x768px) this issue is worse.

**Comment by gabeweb** [comment]
> Hi, could you please check with the latest release if you are able to change the window size?

Hi, the version 0.3.4 allows me to modify the size of the window. Excellent!
