### ISSUE TITLE
[Bug]: Volume gets reset when switching songs

### ISSUE THREAD

**Issue by afonsofrancof** [hiaaryan/wora#25]
### What Happened?

When a song ends and a new one starts playing, it starts at 100% volume.
The audio slider is still in the correct position, and If I click on it again it fixes itself.

### Wora Version

0.3.5

### Operating System

macOS Sequoia

### Steps to Reproduce

Just play a song, change the volume inside the app and then either wait for the song to finish or skip to the next one

### Environment Details

Normal macbook pro speakers

### Severity

Minor

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hiaaryan** [comment]
Hi @afonsofrancof!

Thanks for trying out Wora. Unfortunately, this is a result of my own refactoring sorceries, which resets the volume on every song change. I am releasing a hotfix v0.3.6 shortly to fix this.

Meanwhile, many thanks for contributing to the project. We are open to welcome any QA Testers on our Discord to try out beta and alpha build so these kinds of issues don't occur in future.

Apologies for the inconvenience!

**Comment by afonsofrancof** [comment]
Hey @hiaaryan !
I appreciate this project, I had been looking for a media player/manager for a while, and they all looked 20 years old.
I will be giving you my feedback in case anything else happens :)

**Comment by hiaaryan** [comment]
This is now fixed with v0.3.6 🎉
