### ISSUE TITLE
[Bug]: Wora does not open

### ISSUE THREAD

**Issue by aidenszolosi** [hiaaryan/wora#27]
### What Happened?

`Wora.exe` Fails to Start - Presumed Cause: JavaScript Heap Out of Memory

**Description:**
The `Wora.exe` program fails to start, running into a fatal error related to JavaScript heap out of memory. The program does not open at all and displays error messages when using various troubleshooting techniques.

**Steps to Reproduce:**
1. Download and install `Wora.exe` from the provided source.
2. Run the program using the command: `./Wora.exe --enable-logging`
3. Observe the error messages in the console.

**Expected Behavior:**
The program should start and function as expected without running out of memory.

**Actual Behavior:**
The program fails to start and displays a "JavaScript heap out of memory" error. The error messages indicate issues with memory allocation in the Node.js environment.

**Error Messages:**
```
[31464:0721/124304.498:ERROR:node_bindings.cc(379)] Most NODE_OPTIONs are not supported in packaged apps. See documentation for more details.

<--- Last few GCs --->

[31464:0000324C00164000]    10182 ms: Mark-Compact (reduce) 3986.4 (3998.6) -> 3986.2 (3989.6) MB, pooled: 0 MB, 853.35 / 0.00 ms  (average mu = 0.735, current mu = 0.463) last resort; GC in old space requested
[31464:0000324C00164000]    10501 ms: Mark-Compact (reduce) 3986.2 (3989.6) -> 3986.2 (3989.1) MB, pooled: 0 MB, 318.69 / 0.00 ms  (average mu = 0.613, current mu = 0.000) last resort; GC in old space requested

<--- JS stacktrace --->

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
----- Native stack trace -----

 1: 00007FF779DBDADA uv_cpumask_size+72474
 2: 00007FF779D390EF node::OnFatalError+671
 3: 00007FF77CFD96E4 v8::Function::NewInstance+868
 4: 00007FF77CFD9653 v8::Function::NewInstance+723
 5: 00007FF77B5B77B1 v8::internal::ThreadIsolation::StartOfJitAllocationAt+436305
 6: 00007FF77B5A6B8C v8::internal::ThreadIsolation::StartOfJitAllocationAt+367660
 7: 00007FF77B43EE5C uv_random+4382268
 8: 00007FF7788B0D67 v8::CppHeap::CollectStatistics+22023
 9: 00007FF7788B0FD1 v8::CppHeap::CollectStatistics+22641
10: 00007FF77B51124E v8::String::NewFromUtf8+142
11: 00007FF817EBB181 node_register_module_v125+39185
12: 00007FF817EBB93D node_register_module_v125+41165
13: 00007FF817EB728D node_register_module_v125+23069
14: 00007FF77BB5E141 v8::internal::compiler::CompilationDependencies::FieldTypeDependencyOffTheRecord+2111665
15: 00007FF77BB5BD67 v8::internal::compiler::CompilationDependencies::FieldTypeDependencyOffTheRecord+2102487
16: 00007FF77BB5BD67 v8::internal::compiler::CompilationDependencies::FieldTypeDependencyOffTheRecord+2102487
17: 00007FF77BB5BD67 v8::internal::compiler::CompilationDependencies::FieldTypeDependencyOffTheRecord+2102487
18: 00007FF77BB5BD67 v8::internal::compiler::CompilationDependencies::FieldTypeDependencyOffTheRecord+2102487
19: 00007FF77BB5BD67 v8::internal::compiler::CompilationDependencies::FieldTypeDependencyOffTheRecord+2102487
20: 00007FF77BC7ADC0 v8::internal::compiler::CompilationDependencies::FieldTypeDependencyOffTheRecord+3278128
21: 00007FF77BB8C007 v8::internal::compiler::CompilationDependencies::FieldTypeDependencyOffTheRecord+2299767
22: 00007FF77BB596B3 v8::internal::compiler::CompilationDependencies::FieldTypeDependencyOffTheRecord+2092579
23: 00007FF77B563161 v8::internal::ThreadIsolation::StartOfJitAllocationAt+90625
24: 00007FF778885E91 v8::internal::ThreadIsolation::SplitJitPages+64321
25: 00007FF77888606B v8::internal::ThreadIsolation::SplitJitPages+64795
26: 00007FF77B571837 v8::internal::ThreadIsolation::StartOfJitAllocationAt+149719
27: 00007FF77A4D09BB node::PromiseRejectCallback+2043
28: 00007FF77BB5E141 v8::internal::compiler::CompilationDependencies::FieldTypeDependencyOffTheRecord+2111665
29: 00007FF77BB5BD67 v8::internal::compiler::CompilationDependencies::FieldTypeDependencyOffTheRecord+2102487
30: 00007FF77BB597DC v8::internal::compiler::CompilationDependencies::FieldTypeDependencyOffTheRecord+2092876
31: 00007FF77BB59333 v8::internal::compiler::CompilationDependencies::FieldTypeDependencyOffTheRecord+2091683
32: 00007FF77B562004 v8::internal::ThreadIsolation::StartOfJitAllocationAt+86180
33: 00007FF77B515A44 v8::Function::Call+516
34: 00007FF779DCB8DD node::CallbackScope::CallbackScope+1341
35: 00007FF779DCB5CD node::CallbackScope::CallbackScope+557
36: 00007FF779D5BDE8 node::binding::get_linked_module+14424
37: 00007FF779DC819C node::LoadEnvironment+396
38: 00007FF7780E5728 node::loader::ModuleWrap::SelfSize+14680
39: 00007FF778028654 std::__Cr::vector<v8::CpuProfileDeoptFrame,std::__Cr::allocator<v8::CpuProfileDeoptFrame> >::__alloc+74260
40: 00007FF778F1A70F uv_timer_set_repeat+1137887
41: 00007FF778F1E4B3 uv_timer_set_repeat+1153667
42: 00007FF778F19CBD uv_timer_set_repeat+1135245
43: 00007FF7781DF142 v8::internal::StrongRootAllocatorBase::StrongRootAllocatorBase+483122
44: 00007FF7781E036A v8::internal::StrongRootAllocatorBase::StrongRootAllocatorBase+487770
45: 00007FF7781E0151 v8::internal::StrongRootAllocatorBase::StrongRootAllocatorBase+487233
46: 00007FF7781DE95F v8::internal::StrongRootAllocatorBase::StrongRootAllocatorBase+481103
47: 00007FF7781DEB3D v8::internal::StrongRootAllocatorBase::StrongRootAllocatorBase+481581
48: 00007FF777F1B56B v8::SourceLocation::SourceLocation+56619
49: 00007FF77C3122D2 Cr_z_adler32+5719794
50: 00007FF902A3DBE7 BaseThreadInitThunk+23
51: 00007FF9038FA94C RtlUserThreadStart+44
```

**System Information:**
- OS:
  -  OS Name:                       Microsoft Windows 11 Home
  -  OS Version:                    10.0.26120 N/A Build 26120
- Node.js Version: v20.15.1
- `Wora.exe` Version: 0.3.3 and 0.3.6

**Additional Context:**
- Attempted to increase memory limit using `--max-old-space-size=4096`, but this option is not supported in packaged apps.
- Tried various troubleshooting techniques, including setting environment variables and profiling memory usage, but the issue persists.

**Steps Taken to Troubleshoot:**
1. Increased memory limit using `--max-old-space-size=4096` using environment variables and flags.
2. Ran the executable directly without any additional options.
3. Attempted to profile and debug the application to identify memory usage issues.
4. Ran using windows troubleshooting options
5. Fully removed all traces of Wora and reinstalled

**Request:**
- Guidance on resolving the JavaScript heap out of memory issue.
- Suggestions for optimizing memory usage within the application.
- Any known workarounds or fixes for this problem.

Thank you for your assistance!

### Wora Version

0.3.3, 0.3.6

### Operating System

- OS:   -  OS Name:                       Microsoft Windows 11 Home   -  OS Version:                    10.0.26120 N/A Build 26120

### Steps to Reproduce

1. Download and install `Wora.exe` from the provided source.
2. Run the program using the command: `./Wora.exe --enable-logging`
3. Observe the error messages in the console.

### Environment Details

x64 Intel CPU
16 GB RAM

### Severity

Critical

### Discord Username

aidensoz

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by hiaaryan** [comment]
This is strange, would need some more debugging on the JS side since I can't know what's actually causing this. I'll add a logger in the next update, maybe we can try again to fix this 🛠️

**Comment by aidenszolosi** [comment]
Fixed in newer releases of Wora.
