### ISSUE TITLE
[Bug]: The app crashes when clicking on the album tab

### ISSUE THREAD

**Issue by liuphz** [hiaaryan/wora#28]
### What Happened?

When clicking on the album tab, the album cover will be displayed correctly if less music is imported, but if a lot of music is imported (I imported 1,500 albums), it will crash and exit directly.

### Wora Version

0.3.6

### Operating System

Windows 11

### Steps to Reproduce

The general steps to reproduce are to import more music and then click on the Albums tab

### Environment Details

Windows 11 Home
16 GB RAM
x64 Intel CPU

### Severity

Major

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hiaaryan** [comment]
Right, pagination is a planned feature and this will be fixed in the next update. Please let me know if the same happens with search? 

Tip: You can use Cmd/Ctrl + F

**Comment by liuphz** [comment]
Cool. I'm looking forward to it.

**Comment by hiaaryan** [comment]
Please check this in our beta build, I have added infinite scroll to the albums page.

https://github.com/hiaaryan/wora/releases/tag/v0.4.0-beta0

**Comment by hiaaryan** [comment]
Since, there is no response on this issue, I'll assumed this is fixed and close this for the moment. If you have any feedback, please feel free to comment and open this issue 😄
