### ISSUE TITLE
[Feature]: album art support - folder.jpg

### ISSUE THREAD

**Issue by Not-Sure-Whats-Going-On** [hiaaryan/wora#7]
I'm very impressed with the look and sound of Wora so far - this could replace Tauon as my default player!
I have a couple of issues.

- All albums where the album art that is embedded in the file display fine.  My library has each album in its own directory.  Many (many!) of the albums have the album art not embedded but as a file called folder.jpg in the directory.  These albums show up in Wora with just the default placeholder as the album art.  Can you please give the option to display album art from external files such as folder.jpg?
- Also, the search function doesn't find either Artist or Albumartist from the embedded meta tags.

Thanks!

**Comment by hiaaryan** [comment]
This is a valid issue. I have several albums which have an image in the folder but are not embedded in the song metadata itself.

Currently, Wora is just taking the album art from the song itself and assigns it to the album.

There is a better way to do this, which I have had in mind for some time. We can select any available image available in the album folder `file => /\.(jpg|jpeg|png|gif)$/.test(file)` & fallback to any image available in the song metadata. Also add an option in albums page to edit the cover image.

The search function not indexing the artists is a known issue and this will be fixed when artist page is added in a future update soon 🎉

**Comment by Not-Sure-Whats-Going-On** [comment]
Brilliant, thanks Aaryan!  Look forward to the new release.

**Comment by hiaaryan** [comment]
No worries, just keeping this open till the features are implemented.

**Comment by hiaaryan** [comment]
This issue has been fixed in release v0.3.3. Since artists page is planned in milestone, I am closing this issue 😄
